### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by esskar** [galonsos/line_icons#10]
Hi,

are you planing to maintain this? LineIcons have been updated and added. Will put out a new version with the new LineIcons?

**Comment by galonsos** [comment]
Hi, @esskar. I was not exactly planning to mantain it, but I just posted version 1.3.2 in pub.dev (https://pub.dev/packages/line_icons). Be aware: it has major changes, such as naming. It's aligned with version 1.3.0 of Icons8 collection. Hope you like it!
