### ISSUE TITLE
[Mobile/iOS]: Icons not shown

### ISSUE THREAD

**Issue by Ahmadre** [galonsos/line_icons#13]
## Already done
- flutter clean
- flutter create .

<img width="446" alt="Bildschirmfoto 2020-10-24 um 16 18 15" src="https://user-images.githubusercontent.com/18512224/97084060-a5b21300-1614-11eb-8e52-1c242d978226.png">

**Comment by galonsos** [comment]
Please, upgrade to version 1.3.2, which I just posted in pub.dev (https://pub.dev/packages/line_icons). But be aware: it has major changes, such as naming. Hope you like it!
