### ISSUE TITLE
Null-safety version

### ISSUE THREAD

**Issue by mimarko** [galonsos/line_icons#19]
Any plan to support Flutter 2.0 and null safety?

Thanks for adopting Icon8 for flutter.
Marko

**Comment by AscentionOne** [comment]
@galonsos  Thank you for making this great package and maintaining it up to date! Like this package a lot! I am currently using this package for my project actively hope this can get a null safety upgrade! 😁

**Comment by galonsos** [comment]
Hi, guys. 

As soon as I can, I'll get to it! 

Thank you.

Germán

**Comment by galonsos** [comment]
I'll close this issue since I just released version 2.0.1.

Cheers,

Germán
