### ISSUE TITLE
How to use filled icons instead of outlined?

### ISSUE THREAD

**Issue by Hekhy** [galonsos/line_icons#22]
Well the title basically says it all, but let me explain, on the [Icons8](https://icons8.com/line-awesome) page where all the Line Awesome icons and their names are shown, when you put over one with the mouse cursor it shows you that you have another design of the same icon but filled, since for example I am trying to use the LineIcons.divide but it only shows outlined and I would like all padding inside, I would like to know how I can use them with your package or if they are not implemented suggest that you add them as well because it would be very good to have them.

**Comment by galonsos** [comment]
Hi, @Hekhy.

I think the feature you find in the Icons8 page is just to show the filled icon which inspired the outlined one. In fact, the filled ones (Awesome Icons) aren't even hosted by Icons8 (see https://fontawesome.com/v5.15/icons?d=gallery&p=2). In short: Icons8 Line Icons are inspired by Awesome Icons, just that. 

If you're looking for the filled icons, please take a look at https://pub.dev/packages/font_awesome_flutter.

Thanks.
