### ISSUE TITLE
Misspelled: `LineAwesomeIcons.alternate_wine_glas`

### ISSUE THREAD

**Issue by lukehutch** [galonsos/line_icons#25]
`LineAwesomeIcons.alternate_wine_glas` is missing a final `s`.

**Comment by galonsos** [comment]
Thanks, Luke. I'll fix it as soon as I get some free time :)

**Comment by galonsos** [comment]
Version 2.0.3 has already been published to fixed this. Thank you!

**Comment by lukehutch** [comment]
Thanks!
