### ISSUE TITLE
Icons are not displaying correctly

### ISSUE THREAD

**Issue by franklinharper** [galonsos/line_icons#4]
Thanks for converting this great icon set to Flutter!

Unfortunately when I run your demo code I see this 😞 

![image](https://user-images.githubusercontent.com/445126/58443523-347cd200-80a7-11e9-9cee-d42674d5dd4d.png)

**Comment by mahmoudalaa97** [comment]
Try to use  `flutter clean` ,stop run app , and run again

**Comment by galonsos** [comment]
Thanks, @mahmoudalaa97. Did you solve it, @franklinharper ?

**Comment by jangerhard** [comment]
I'm not OP, but can confirm that `flutter clean` and stopping the app did indeed fix the icons for me.

**Comment by Ahmadre** [comment]
Flutter clean doesn't work for me on Flutter web: https://github.com/galonsos/line_icons/issues/12

**Comment by galonsos** [comment]
Please, upgrade to version 1.3.2, which I just posted in pub.dev (https://pub.dev/packages/line_icons). But be aware: it has major changes, such as naming. Hope you like it!
