### ISSUE TITLE
(line_icons: ^1.1.0) not available - not published

### ISSUE THREAD

**Issue by Stavrosfil** [galonsos/line_icons#6]
When i try to use the icons as a dependency, i get the error: 
```
 line_icons ^1.1.0 which doesn't match any versions, version solving failed.
```
Seems like it is not updated/published yet in the official website.
(Also please include the satellite icon if possible, i really love and need it :) )

**Comment by galonsos** [comment]
Please, upgrade to version 1.3.2, which I just posted in pub.dev (https://pub.dev/packages/line_icons). But be aware: it has major changes, such as naming. Hope you like it!
