### ISSUE TITLE
Package on pub.dev outdated

### ISSUE THREAD

**Issue by clicks** [galonsos/line_icons#7]
The last version on pub.dev was published on Jan 14, 2019 and is missing lots of newer icons, which you included in your last commit.

**Comment by RosalieWessels** [comment]
Hi, 
I was having the exact same problem. In one of the other issues, @gavzla answered and suggested that you use this piece of code to import line_icons:

https://user-images.githubusercontent.com/11657368/76921226-7cb9ea80-689b-11ea-9963-02285853ead9.png 
(this is his image)

Download your packages again and it should work. Hope this helps!

**Comment by galonsos** [comment]
Hi, @clicks  and @RosalieWessels. Please, upgrade to version 1.3.2, which I just posted in pub.dev (https://pub.dev/packages/line_icons). But be aware: it has major changes, such as naming. Hope you like it!
