### ISSUE TITLE
Missing Facebook icons

### ISSUE THREAD

**Issue by lucasmaffazioli** [galonsos/line_icons#9]
Thanks for the plugin! 

All the Facebook Icons are the same: facebook, facebook_square, facebook_official, all of them are like this:

![image](https://i.imgur.com/uRgnp3t.png)

**Comment by galonsos** [comment]
Hi, @lucasmaffazioli. Please, upgrade to version 1.3.2, which I just posted in pub.dev (https://pub.dev/packages/line_icons). But be aware: it has major changes, such as naming and a lot more icons, so hopefully you'll find any Facebook icon you're looking for. Hope you like it!
